services:
  - type: web
    name: user-management-api
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 3000
      - key: CORS_ORIGIN
        value: https://user-management-9vx5.vercel.app 